### ISSUE TITLE
Make RfQ a real document

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2427] opened 2017-09-12 06:44 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the RfQ window is a document but only halfway.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Make the RfQ Window a real document with document status and document actions.

**Comment by teosarca** [comment] 2017-09-12 10:28
Please consider implementing https://github.com/metasfresh/metasfresh/issues/2432 first and then use that process to transform RfQ to a document.

**Comment by teosarca** [comment] 2017-09-12 10:30
duplicate of https://github.com/metasfresh/metasfresh/issues/1842

**Closed by teosarca** 2017-09-12 10:30 UTC
Labels: type:enhancement
