### ISSUE TITLE
Distribution Editor Move HU takes ages

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3542] opened 2018-02-22 08:53 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
When selecting a Distribution Orderline and starting the action "move HU" the dropdown list for HU does not come to an end (pending).
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment] 2018-02-22 09:00
took a quick look on how the process param is configured.... and it's a simple M_HU_ID search field (without any filtering).
I suspect it's a problem of that particular underlying database.

![image](https://user-images.githubusercontent.com/1244701/36528976-9277ba52-17bf-11e8-81d1-4ddc3f8d71d1.png)

**Comment by teosarca** [comment] 2018-02-22 09:04
tried on w101, and works nicely: https://w101.metasfresh.com:8443/window/540373

**Comment by metas-mk** [comment] 2018-03-02 13:26
Asked @metas-ts for remote debugging.

**Comment by metas-ts** [comment] 2018-03-02 20:15
hi @teosarca  @metas-mk , 
while waiting, i looked at the DB-status and saw the first part of the select that is running in on the DB:
```sql
SELECT M_HU.M_HU_ID,NULL,
	concat_ws('_', NULLIF (TRIM(M_HU.Value), ''), 
	( select  NULLIF (TRIM(M_HU_PI_Version.Name), '') from M_HU_PI_Version where M_HU_PI_Version.M_HU_PI_Version_ID=M_HU.M_HU_PI_Version_ID)),
M_HU.IsActive FROM M_HU
WHERE 
	/* filter */ 
	unaccent_string(
		concat_ws(
			'_', 
			NULLIF (TRIM(M_HU.Value), ''), 
			( select  NULLIF (TRIM(M_HU_PI_Version.Name), '') from M_HU_PI_Version where M_HU_PI_Version.M_HU_PI_Version_ID=M_HU.M_HU_PI_Version_ID)
		), 1
	) ILIKE unaccent_string('%1%', 1)
	AND  /* active */ (	...
```
so, this is why it takes so long. However, i remembered that i recently implemented https://github.com/metasfresh/metasfresh-webui-api/issues/878 ..i applied its migration script on the DB in question et viola :triumph:
I tested a few cases and it works fine now.

**Comment by metas-ts** [comment] 2018-03-05 07:59
is a duplicate of metasfresh/metasfresh-webui-api#878

**Closed by metas-ts** 2018-03-05 07:59 UTC
Labels: priority:high, type:bug
