### ISSUE TITLE
If a purchase order is reactivated, no receipt shall be possible

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1209] opened 2017-03-27 14:47 UTC
### Is this a bug or feature request?

Bug

### What is the current behavior?

If you create a purchase order, then receipt schedules are created, and the goods can be received via "Wareneingang (POS)". If the purchase order is reactivated, then the goods can *still* be received, which shall not be the case.

#### Which are the steps to reproduce?

* create and complete a purchase order
* make sure that the order can be received via "Wareneingang (POS)"
* reactivate the purachse order

=> can still be received

### What is the expected or desired behavior?

While the purchase order is reactivated, no receipt shall be possible. Possibly existing receipt schedules shall be deleted again.

Also please take care that receipt schedules that were in the process of beeing created (async) while the reactivation happened are disposed.

**Comment by metas-mk** [comment] 2017-03-31 09:10
https://github.com/metasfresh/metasfresh/issues/1232 is obsolet.

**Comment by teosarca** [comment] 2017-03-31 10:52
checked again, cannot reproduce because the issue was already fixed on #1166 .
i.e. on purchase order reactivation the receipt schedules are deleted!

**Closed** 2017-03-31 10:54 UTC
Labels: bug
