### ISSUE TITLE
New Document "Source of Supply"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3237] opened 2017-12-20 11:32 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have a document like "Source of Supply" in metasfresh.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
When shipping a product, and the receiver of the product demands a source of supply (new flag in businesspartner customer), then a new document called "source of supply" shall be created/ printed out together with the shipment note (shipment document). The source of supply document shall show the following data:
a) 1 page per product and lot/ charge No.
b) document name and reference to shipment no and date
c) productname
d) product value
e) quantity delivered/ shipped
f) lot/ charge no
g) best before date
h) sub-producer/ producer name

**Comment by metas-dh** [comment] 2018-01-10 13:39
Results of IT
tested in mf15

* new flag for Source of Supply: 
  * in bpartner window main window, not customer tab, OK?
  * "IsSourceSupplyCert": translation for de_DE needed
  * only available in Swing
* checked with lc: jasper document is customer specific and cannot be tested in mf15cloudit, need to check where i can test
* regression testing: inout jasper report working fine w/ and w/o the flag checked: OK

**Comment by metas-dh** [comment] 2018-01-25 12:05
Source of Supply itself will be tested by metas-mk on customer db.

**Comment by metas-rc** [comment] 2018-03-26 13:16
Moving to done since the customer issue was already closed for a while

**Closed by metas-rc** 2018-03-26 13:16 UTC
Labels: branch:master, branch:release, priority:high, type:enhancement
