### ISSUE TITLE
HU planned after Purchase Order, destroyed after material receipt

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3086] opened 2017-11-27 07:36 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, after creating a Purchase Order, there are Handling Units created and set into status "planned". After doing the Material Receipt these HU are "destroyed".
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The HU shall not be destoyed but used for material receipt. If not used then at least delete the unused HU.

Last HU before purchase order:
![image](https://user-images.githubusercontent.com/13365687/33255429-d642d25a-d34d-11e7-8443-bbfe4181ca17.png)

Last HU after purchase order:
![image](https://user-images.githubusercontent.com/13365687/33255451-ea279c6a-d34d-11e7-932b-bd1e5897f8e6.png)

Last HU after Material Receipt (info: Destroyed HU are not shown anymore):
![image](https://user-images.githubusercontent.com/13365687/33255464-fcee8afc-d34d-11e7-97d5-fc13b92c03fb.png)

**Comment by metas-mk** [comment] 2017-11-27 09:22
Talked w/ @teosarca Get rid of pre-generated HU after Purchase Order/ material Receipt Candidates

**Comment by teosarca** [comment] 2017-11-27 14:03
update: Planning HUs are no longer generated when the receipt candidate is created.
More, i've also dropped the M_ReceiptSchedule.IsHUPrepared column because it no longer makes sense.

**Comment by teosarca** [comment] 2017-11-27 14:03
note to IT: 
* regression, on swing too

**Comment by metas-ts** [comment] 2017-12-04 12:56
cherry-picked to `release`

**Comment by metas-dh** [comment] 2017-12-07 08:21
Results of IT1
tested in mf15

WebUI:
1. Purchase Order is completed and Material Receipt Candidates are created: no Planning HUs: OK
2. HU Editor in Material Receipt Candidates is opened, to create material receipt: Planning HUs: OK
3. Material Receipt created: Planning HUs become Active: OK
4. Transform Planning HUs Use "TU to new TUs" to take TUs out off the LU: LU is Destroyed, TUs remain Planning: OK
5. Material Receipt created for 1 TU, close the Editor: 1 TU is now Active, the other is Destroyed: OK

question:
the destroyed LU from step 4. was shown in HU Editor after the Transform, but not the Planning TUs; also the destroyed TU from step 5 was shown in HU Editor: they disappeared after clearing the filter params (had filtered for my product first), is that bc of caching? 

after 4.:
![2017-12-07 08_50_45-metasfresh](https://user-images.githubusercontent.com/18696715/33705200-a9c9228a-db2f-11e7-94b7-2ff1c624d0ae.png)

after 5:
![2017-12-07 08_57_49-metasfresh](https://user-images.githubusercontent.com/18696715/33705219-b664bee6-db2f-11e7-8434-df7070e42b85.png)

after clearing filter:
![2017-12-07 09_18_20-metasfresh](https://user-images.githubusercontent.com/18696715/33705232-c47e186a-db2f-11e7-8324-6458673f5a98.png)


ToDo: Swing testing & regression

**Comment by teosarca** [comment] 2017-12-07 08:27
> the destroyed LU from step 4. was shown in HU Editor after the Transform, but not the Planning TUs; also 
> the destroyed TU from step 5 was shown in HU Editor: they disappeared after clearing the filter params 
> (had filtered for my product first), is that bc of caching?

nop, it's because of https://github.com/metasfresh/metasfresh/issues/3088.
Everything related to transform and destroyed HUs left behind is because of that task.

**Comment by metas-dh** [comment] 2017-12-07 10:41
thx for the info!

Swing:
1. Purchase Order is completed and Material Receipt Candidates are created: no Planning HUs: OK
2. HU Editor in Material Receipt Candidates is opened, to create material receipt: Planning HUs: OK
3. Material Receipt created: Planning HUs become Active: OK
4. Transform Planning HUs Use "TU to new TUs" to take TUs out off the LU: LU is Destroyed, TUs remain Planning: OK
5. Material Receipt created for 1 TU, close the Editor: 1 TU is now Active, the other is Destroyed: OK

difference:
=> when you open the HU Editor in Material Receipt Candidates, then you get Planning HUs, both in Swing and WebUI: OK
but: 
* in Swing, when you close the Editor without doing anything and reopen it (with the same Gebindekonfig), you get the same HUs (same values) to receive / work with
* in WebUI, the Planning HUs remain after closing the Editor (you can still find them in Handling Unit Editor window), but when you open the Editor in Material Receipt Candidates again, you get new Planing HUs (different HU values), and the old ones are destroyed
=> why this difference?

**Comment by teosarca** [comment] 2017-12-07 16:34
@metas-dh  agreed with @metas-mk  to create a follow-up for that issue: https://github.com/metasfresh/metasfresh-webui-api/issues/729

Besides that, i think everything is fulfilled, right?

**Comment by metas-dh** [comment] 2017-12-08 13:45
@teosarca thx for the info, closing this one.

**Closed by metas-dh** 2017-12-08 13:45 UTC
Labels: branch:master, branch:release, type:enhancement
