### ISSUE TITLE
Reactivated Purchase Orders fails when changing Packing Material in Orderline

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1167] opened 2017-03-16 14:02 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Reactivated Purchase Orders fails when changing Packing Material in Orderline. Seems to be connected to remaining Material Receipt Schedule lines.
### What is the expected or desired behavior?

![image](https://cloud.githubusercontent.com/assets/13365687/23999721/7dff953c-0a59-11e7-8336-54b519d43378.png)

**Comment by teosarca** [comment] 2017-03-16 15:09
duplicate of #1166

**Closed by teosarca** 2017-03-16 15:09 UTC
Labels: bug
