### ISSUE TITLE
Product Document Note Translation not set in orderline / order confirmation

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4804] opened 2018-11-28 11:05 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Follow-up of #4787:
When a Product Document Note Translation exists, it is not set in orderline / order confirmation. (tested with menu language en_US)
#### Which are the steps to reproduce?
1. Have a Product Document Note Translation, e.g. for en_US (also have one in de_DE, for comparison)
2. Set en_US as language for a bpartner
3. Create a sales order for that bpartner and use the resp. product:
* product note in tooltip is the de_DE note: NOK
* check the order confirmation Jasper: product note is the de_DE note: NOK

### What is the expected or desired behavior?

Product Document Note Translation shall be set.

tsa LE: Product's Document Note shall be displayed using BPartner's language.
In the example above, it shall be in en_US.

ts: I think it should be a physical column in C_OrderLine, so a given (completed) order's jasper doesn't changed when the product document note changes.

**Comment by metas-ts** [comment] 2018-12-04 12:34
duplicate of #4787

**Closed by metas-ts** 2018-12-04 12:34 UTC
Labels: type:bug
