### ISSUE TITLE
Provide Rollout and Release for WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#699] opened 2016-12-12 11:48 UTC
1. create binary release for already published code of WebUI Frontend and Backend
1. create update and deploy scripts

**Comment by metas-ts** [comment] 2016-12-13 05:49
@metasnw i'm on it.
I created #698 branch (`FRESH-1013-gh698`) for the same purpose.

**Comment by metas-ts** [comment] 2016-12-13 05:52
closing this issue as duplicate of #698

**Closed by metas-ts** 2016-12-13 05:52 UTC
Labels: enhancement
