### ISSUE TITLE
Customer Returns for HU more than 1 Document

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1869] opened 2017-06-22 06:27 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Sometimes, when Creating a Customer Return from Shipment and selected HU, then 2 Customer Return Document are created.
#### Which are the steps to reproduce?
Please ping mk for testcases (570058, 570059).
### What is the expected or desired behavior?
The process shall only create the correct amount of Return Documents for the correct Business Partner.

**Comment by metas-rc** [comment] 2017-06-23 06:59
Additional bugs :
* There are no lines for the TU
* QtyTU and packing material are not displayed in the product line

**Comment by metas-rc** [comment] 2017-06-23 11:03
* Picking termina's HUEditor also contains the HUs created via a manual customer return (NOK)

**Comment by metas-ts** [comment] 2017-06-28 03:50
@metas-rc please avoid string like "Fix #1234" in your commit messages (also with line breaks in between), or the issue will be closed by github upon integration into master...idk how to switch this off

**Comment by metas-rc** [comment] 2017-06-28 08:37
Followup for Hus coming from Verdichtung POS: https://github.com/metasfresh/metasfresh/issues/1912

**Comment by metas-rc** [comment] 2017-06-28 08:38
Note for IT

Please do regression testing for: 
* Manual customer returns
* Vendor returns
* Garbage

**Comment by metas-ts** [comment] 2017-06-28 12:49
cherry-picked into the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/189/

**Comment by metas-rc** [comment] 2017-06-30 09:23
Bug found

Steps to reproduce:
* Create a sales order with product P1 on IFCO with capacity x 10. Complete
* Create a purchase order for the same product
* Go to Wareneingang POS , open with a lutu config with qty TU = 17
* Split the HU: qty TU 7
* Select both resulting HUs, press OK
* Go to Picking terminal, HUEditor, select oth HUs
* Go to the  shipment schedule of the sales order above, create a shipment based on the qty picked
* run Return From Customer in this shipment, only for the HU with qtyTU = 7
* => NOK: The customer return does not have a TU line

After debugging I found out the root problem is that HUs resulting from split do not have M_HU_PI_Item_Product set.
The vendor and customer return logic rely upon this value veing set for taking the TU product and qty of the aggregated HU. But since the M_HU_PI_Item_Product does not exist, the logic is not applied.
Note: The HU resulting from a split does not have M_LU_TU_Config value either.

**Comment by metas-lc** [comment] 2017-07-04 13:42
Customer return:
- tested in https://github.com/metasfresh/metasfresh/issues/1306 OK
- follow-up for HUs that were split before/after shipment: https://github.com/metasfresh/metasfresh/issues/1496

Regression:
Vendor return:

Material disposal:

**Closed** 2017-07-05 14:20 UTC
Labels: branch:master, branch:release, type:bug
