### ISSUE TITLE
New Picking&Packing Workflow

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4577] opened 2018-09-12 03:14 UTC
### Note to IT
Regression:
* swing picking terminal
* webui picking terminal (not this one)
* e2e is really needed!!!

**Comment by metas-dh** [comment] 2018-10-17 10:41
Results from regression testing
tested in mf15 / release

**I. WebUI:**
1. picking actions (pick HU / pick CU) and selecting source HU not available in original picking terminal anymore: **NOK**

2. picking from manufacturing order not working anymore, **NOK**
=> in the overlay `Pick`, after picking a HU and selecting a shipment schedule & picking slot, you get  error: 
```
"Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "NullPointerException: qtyPicked"
path: "/rest/api/process/ADP_540875/1001644/start"
```

<details>

```
{timestamp: 1539690154034, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "NullPointerException: qtyPicked"
path: "/rest/api/process/ADP_540875/1001644/start"
status: 500
timestamp: 1539690154034
trace: ["org.adempiere.exceptions.AdempiereException: NullPointerException: qtyPicked",…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: NullPointerException: qtyPicked"
1: "	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)"
2: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:865)"
3: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
4: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
5: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
6: "	at org.adempiere.ad.trx.api.ITrxManager.callInThreadInheritedTrx(ITrxManager.java:250)"
7: "	at de.metas.handlingunits.picking.candidate.commands.PickHUCommand.perform(PickHUCommand.java:91)"
8: "	at de.metas.handlingunits.picking.PickingCandidateService.pickHU(PickingCandidateService.java:85)"
9: "	at de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Pick.pickHU(WEBUI_M_HU_Pick.java:182)"
10: "	at de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Pick.doIt(WEBUI_M_HU_Pick.java:172)"
11: "	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:296)"
12: "	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
13: "	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
14: "	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
15: "	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
16: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
17: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
18: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
19: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
20: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
21: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
22: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
23: "	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
24: "	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
25: "	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
26: "	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
27: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:332)"
28: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:309)"
29: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:262)"
30: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
31: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:261)"
32: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
33: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
34: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:260)"
35: "	at sun.reflect.GeneratedMethodAccessor378.invoke(Unknown Source)"
36: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
37: "	at java.lang.reflect.Method.invoke(Method.java:498)"
38: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
39: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
40: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
41: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
42: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
43: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
44: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
45: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
46: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
47: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
48: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
49: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
50: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
51: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
52: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
54: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
57: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
58: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
61: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
64: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
67: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
68: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
70: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
71: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
74: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
78: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
79: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
82: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
83: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
86: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
87: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
90: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
91: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
94: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
95: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
96: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
97: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
98: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
99: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
[100 … 121]
100: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
101: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
102: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
103: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
104: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
105: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
106: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
107: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
108: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
109: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
110: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
111: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
112: "	at java.lang.Thread.run(Thread.java:748)"
113: "Caused by: java.lang.NullPointerException: qtyPicked"
114: "	at de.metas.handlingunits.picking.PickingCandidate.<init>(PickingCandidate.java:49)"
115: "	at de.metas.handlingunits.picking.PickingCandidate$PickingCandidateBuilder.build(PickingCandidate.java:49)"
116: "	at de.metas.handlingunits.picking.candidate.commands.PickHUCommand.getOrCreatePickingCandidate(PickHUCommand.java:138)"
117: "	at de.metas.handlingunits.picking.candidate.commands.PickHUCommand.performInTrx(PickHUCommand.java:102)"
118: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
119: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
120: "	... 110 more"
121: ""
```
</details>






**II. Swing:**
1. Barcode scanning not working as before (1st window Komm Terminal): 
* nothing happens after entering HU value or SSCC in `Barcode`, no error,  console:

<details>

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.addAll(ImmutableCollection.java:244)
	at de.metas.fresh.picking.form.FreshPackingMd.setTableRowSearchSelectionMatcher(FreshPackingMd.java:722)
	at de.metas.fresh.picking.form.SwingPickingOKPanel.setTableRowSearchSelectionMatcher(SwingPickingOKPanel.java:682)
	at de.metas.fresh.picking.form.SwingPickingTerminalPanel.setTableRowSearchSelectionMatcher(SwingPickingTerminalPanel.java:700)
	at de.metas.fresh.picking.form.SwingPickingTerminalPanel.onBarcodeSearch0(SwingPickingTerminalPanel.java:794)
	at de.metas.fresh.picking.form.SwingPickingTerminalPanel.onBarcodeSearch(SwingPickingTerminalPanel.java:732)
	at de.metas.fresh.picking.form.SwingPickingTerminalPanel.access$200(SwingPickingTerminalPanel.java:99)
	at de.metas.fresh.picking.form.SwingPickingTerminalPanel$2.propertyChange(SwingPickingTerminalPanel.java:155)
	at org.adempiere.util.beans.WeakPropertyChangeListener.propertyChange(WeakPropertyChangeListener.java:168)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at de.metas.adempiere.form.terminal.AbstractTerminalField.firePropertyChange(AbstractTerminalField.java:116)
	at de.metas.adempiere.form.terminal.AbstractTerminalTextField.firePropertyChanged(AbstractTerminalTextField.java:137)
	at de.metas.adempiere.form.terminal.swing.SwingTerminalTextField.access$200(SwingTerminalTextField.java:77)
	at de.metas.adempiere.form.terminal.swing.SwingTerminalTextField$TextFieldActionListener.actionPerformed(SwingTerminalTextField.java:127)
	at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at javax.swing.JTextField.postActionEvent(JTextField.java:721)
	at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
	at javax.swing.JFormattedTextField$CommitAction.actionPerformed(JFormattedTextField.java:1123)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
</details>


* picking line is not marked with 'H' in column B as it used to be: **NOK**
* open HU Editor in 2nd window: the HU shows up and is pre-selected, though (if the attribute does not match, you have to  uncheck "Consider attributes" first to have the HU displayed): **OK**
* when u close the 2nd window again, the 'H' is now displayed: **OK**



2. opening 2nd window in Picking Terminal not working when different PIs ordered: **NOK**
* have 2 sales orders, same bpartner, same product, same warehouse
* 1 order has e.g. PI: IFCO, the other has No Packing Item or G1
* Picking Terminal: 1 line for the product with overall qty
* select the line, click OK to open 2nd window: 

```
INFO 22754 --- [WT-EventQueue-0] org.compiere.apps.ADialog         
Error - Got more than one result: [HUPIItemProductId(repoId=101), HUPIItemProductId(repoId=3010009)]
```

3. Picking using HUs from HU Editor: OK so far

4. Picking using Verteilen action: OK so far

5. Picking using Hinzuf... & Entfer...: OK so far

**Comment by metas-ts** [comment] 2018-10-17 12:15
accicental close via commit message

**Comment by teosarca** [comment] 2018-10-17 12:43
@metas-dh  Updates so far:

I. WebUI:

> 1. picking actions (pick HU / pick CU) and selecting source HU not available in original picking terminal anymore: NOK

Introduced & fixed on https://github.com/metasfresh/metasfresh/issues/4609#issuecomment-430610626 .


> 2. picking from manufacturing order not working anymore, NOK

shall be fixed

II. Swing:

> 1. Barcode scanning not working as before (1st window Komm Terminal):

shall be fixed

**Comment by teosarca** [comment] 2018-10-17 13:12
> picking line is not marked with 'H' in column B as it used to be: NOK

did a quick test and for me it works, see below
![image](https://user-images.githubusercontent.com/1244701/47088550-70091100-d227-11e8-8b48-bdc1ac744652.png)

**Comment by teosarca** [comment] 2018-10-17 13:32
> 2. opening 2nd window in Picking Terminal not working when different PIs ordered: NOK
> * have 2 sales orders, same bpartner, same product, same warehouse
> * 1 order has e.g. PI: IFCO, the other has No Packing Item or G1
> * Picking Terminal: 1 line for the product with overall qty
> * select the line, click OK to open 2nd window:
```
INFO 22754 --- [WT-EventQueue-0] org.compiere.apps.ADialog         
Error - Got more than one result: [HUPIItemProductId(repoId=101), HUPIItemProductId(repoId=3010009)]
````


shall be solved too

**Comment by metas-dh** [comment] 2018-10-18 13:56
Results of IT1
tested in mf15

**I. SetUp**
1. create a purchase order and material receipts for the product you want to test with;
* create sev. material receipts, so you have >1 VHU to pick from
* set different expiring dates for the VHUs
* set Lot No. for some
2. create a warehouse type that you can set in your warehouse(s) used in the sales orders
3. create transportation orders, with different shippers
4. in the bpartner you want to use as customer, set "Delivery via": Shipper
=> i did not find any place where i could set a specific shipper for my bpartner or the resp. bpartner group
5. make sure the testcustomer you want to use has a valid address set (valid zip code!)
6. set up e.g. Der Kurier as shipper

**II. Test**
1. Create a sales order for your testcustomer:
* select a warehouse from the type you created
* create >1 orderline for your testproduct, with qty >1 each
* make sure shipper (e.g. Der Kurier) is set in the orderline(s)
=> had to set that via sql! is not displayed in WebUI or Swing!

2. Open new Picking Terminal:  your sales order is displayed with
a. the resp. product (1 line per product): **OK**
b. shipper from orderline: **OK**
c. no. of orderlines: **OK**
d. line net amt of the orderlines: **OK**
e. the warehouse type of the warehouse from the order: **OK**
f. shipment date & date ready: **OK**
g. Lieferkontakt: the picker: that was set for my sales orders only **after** i did the picking, is that ok? not sure how user / roles are set up at the customer...
=> need to test the Unlock / Unlock all actions with different users

3. Select your line, and call `Pick`action: 2nd window opens with
a. 1 line per orderline: **OK**
b. warehouse locator is displayed (with no. of row / aisle etc.): **OK**
c. Lot no. of the HU which is available for picking (if set, if not it's empty): **OK**
d. Expiring date of the HU to pick from:
     * if there are >1 HUs to pick from with different expiring dates, then they are sorted by that date => the one with the expiring date closest to date of picking is displayed in the first line: **OK**
e. RepackNumber: to be set by customer, afaiu?
f. Bruch: if set in the VHU, afaiu, need to test that
g. Quantity: the qty available in the VHU you can pick from if that is < qty ordered OR the qty ordered, if qty ordered is displayed: **OK** 
h. Pick Status: To be Picked

4. Select each line and use pick action: => status is updated to "Picked"

5. Select all lines, and use Pack to action:
a. modal window opens where you can select a packing item
b. select a packing item, and click OK => picked VHUs are packed together in this packing item

6. Check Handling Unit Editor:
a. VHUs you picked from have qty decreased accordingly, status: active: **OK**
b. new HU created, type: as selected in 5.b., status: picked: **OK**

7. in Picking Terminal, now select action 4Eyes Review:
a. QR Code pops up: **OK**
b. copy code from this (in inspect)

8. open Run QR Code from menu (shall be available from everywhere , see: https://github.com/metasfresh/metasfresh-webui-frontend/issues/2015)
a. Barcode field opens: **OK**
b. Enter copied code, Enter: new modal window "Review" opens, : **OK**

9. in modal window Review, check the lines:
a. lines from Picking Terminal are displayed, with product etc., Quantity: empty: **OK**
b. set the quantity:
   * qty </> than qty picked: status: Rejected: **OK**
   * qty = qty picked: status: Approved: **OK**

10. use "Process" action (atm, you have to click somewhere else and then back into the modal, to get the Process action displayed, and the 4Eyes Review & Pack To actions are still displayed: NOK, will be handled in https://github.com/metasfresh/metasfresh-webui-frontend/issues/2014):
a. modal window opens for selecting a transportation order: **OK**
b. select a transportation order, OK => process for creating a shipment, invoice, and adding the shipment to the transportation order is started: **OK**

11. Check the shipment:
a. shipment lines for each line from picking terminal is displayed, with correct qty: **OK**
b. shipment line for the packing item you selected is displayed: **OK**

12. Check the invoice:
a. invoice lines for each line from picking terminal is displayed, with correct qty: **OK**
b. invoice line for the product shows the packing item from the order, not the one selected in picking: **NOK** i think
c. invoice line for the packing item: i did not get anything in the invoice for the packing item, maybe bc it was not on the sales pricelist: how is this supposed to work?

13. Check the transportation order:
a.  shipment is displayed in the order: **OK**
b. related documents: shipment and Der Kurier Delivery Order, if you selected this as the shipper / it was set as shipper in the transportation order: **OK**

14. Check the Der Kurier Delivery Order:
a. orderline with the correct data (from bpartner etc.) displayed
b. attachments:
   * Der Kurier Label: **OK**
   * Delivery ORder csv file: **OK**

15. Check Handling Unit Editor:
=> the HU created in picking now has status: Shipped: **OK**


**III. problems / questions**
1. no filter available in new Picking Terminal, is that not needed?

2. Lieferkontakt was only set after i did the picking, is that ok? see 2.g.

3. * the "Review" modal window remained displayed, with the lines marked as "Approved", after the process ran; there was no notification or anything that the process was successful (just info in notification about shipment & invoice being created); 
* also, when i opened that modal again with Run QR code, and used the same code, i could select the "Process" action again, for the same lines (got a notification that the picking was already processed, but only **after** i selected a transportation order: **NOK** i think, at least not very intuitive / user friendly

4. shouldn't there be a possibility to Unpick / Reverse the Pack to actions, like you can Unpick / Reverse the processing in the old picking terminal?

5. what shall happen after i select the "Will not be picked" action, esp. regarding the orderline / shipment schedule / invoice candidate??

6. Shipper info is taken from orderline, but not displayed in the orderline in WebUI / Swing ( at least not in the testing db)

7. if i have a certain shipper set in the orderlines, shall transportation orders with a different shipper set be selectable in the "Process" action?

8. the invoice (product line) showed the packing item that was selected in the order, not the one selected in the picking process: **NOK** i think

**9. qty available for picking < qty ordered**
=> the qty displayed in the picking terminal, 2nd window, that you can pick is the qty available in the VHU, not the qty ordered
=> if you pick that qty, the next thing you can do is pack to, you cannot add / pick more
=> when you go through the process of packing, approving and processing, then the shipment is created with the overall qty you picked, but the invoice is missing the orderline for which you did only partial picking, the IC for that is not invoiced (probably bc the qty delivered < qy ordered)

**Comment by metas-dh** [comment] 2018-10-22 15:10
problems from latest e2e:
* Unpick action not working: https://github.com/metasfresh/metasfresh-webui-api/issues/1075

* Process picking action not working: https://github.com/metasfresh/metasfresh-webui-api/issues/1074

**Comment by teosarca** [comment] 2018-10-23 10:39
> 5. what shall happen after i select the "Will not be picked" action, esp. regarding the orderline / shipment schedule / invoice candidate??

the shipment schedule will be closed as is.
about invoice candidate, ... nothing.

@metas-mk  wdyt?

**Comment by metas-dh** [comment] 2019-02-18 07:38
closing this since it was tested already and now gets included in weekly e2e; new problems will be solved in new issues.

**Closed by metas-dh** 2019-02-18 07:38 UTC
Labels: branch:master, branch:release, type:enhancement
