### ISSUE TITLE
Copy BOM Consumer Label Fields to PP Order BOMLine

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4273] opened 2018-06-23 08:22 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The new Fields created in https://github.com/metasfresh/metasfresh/issues/4264 are not yet copied to PP Order BOMLine.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Copy the Field content to those new Fields during PP_Order creation (as usual).

**Comment by metas-lc** [comment] 2018-06-28 13:44
IT
1. go to Bill Of Material window and update CU Label Qty and Show Sub BOM ingredients to some lines of Salad
2. Go to Manufacturing Order and create a new one
=> error: Assumption failure: repoId > 0 but it was 0
<details/>

2018-06-28 15:41:38.947  WARN 21589 --- [WT-EventQueue-0] org.compiere.model.GridTab               : Failed executing callout on GridField[M_Product_ID=2005577]. 
 Error message: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: repoId > 0 but it was 0 
 CalloutInstance: AnnotatedCalloutInstance{org.eevolution.callout.PP_Order@757e7783}

org.adempiere.ad.callout.exceptions.CalloutExecutionException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: repoId > 0 but it was 0
	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:28)
	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:25)
	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.executePointcut(AnnotatedCalloutInstance.java:161)
	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.execute(AnnotatedCalloutInstance.java:122)
	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)
	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)
	at org.compiere.model.GridTab.processCallout(GridTab.java:3339)
	at org.compiere.model.GridTab.processFieldChange(GridTab.java:3260)
	at org.compiere.grid.GridController.dataStatusChanged(GridController.java:1263)
	at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2696)
	at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2662)
	at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3315)
	at org.compiere.model.GridTable.setValueAt(GridTable.java:1235)
	at org.compiere.grid.GridController.vetoableChange(GridController.java:1742)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
	at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
	at org.compiere.grid.ed.VLookup.actionCombo(VLookup.java:1043)
	at org.compiere.grid.ed.VLookupAutoCompleter.setUserObject(VLookupAutoCompleter.java:379)
	at org.compiere.apps.search.FieldAutoCompleter.mouseClicked(FieldAutoCompleter.java:619)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: repoId > 0 but it was 0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.adempiere.util.Check.mkEx(Check.java:108)
	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)
	at org.adempiere.util.Check.assumeGreaterThanZero(Check.java:405)
	at org.adempiere.warehouse.WarehouseId.<init>(WarehouseId.java:65)
	at org.adempiere.warehouse.WarehouseId.ofRepoId(WarehouseId.java:42)
	at org.eevolution.callout.PP_Order.findPP_Product_Planning(PP_Order.java:182)
	at org.eevolution.callout.PP_Order.onProductChanged(PP_Order.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.executePointcut(AnnotatedCalloutInstance.java:152)
	... 49 common frames omitted

2018-06-28 15:41:38.948  INFO 21589 --- [WT-EventQueue-0] org.compiere.apps.ADialog                : Error - Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:
Assumption failure: repoId > 0 but it was 0
</details>
will be fixed in https://github.com/metasfresh/metasfresh/issues/3463

**Closed** 2018-06-29 11:35 UTC
Labels: branch:master, good first issue, type:enhancement
