### ISSUE TITLE
Enhanced Pricing, allowing detailed individual Pricesystems per Product and Businesspartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3833] opened 2018-04-11 06:53 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, prices are calculated based on Product Prices (via Price system-Pricelist-PricelistVersion) and matching Discount Rules that are defined in Discount Schema and added to Business partner. In case a Business partner shall have individual prices for a product, then this has to be done in the Product price itself and the Partner then gets an individual Pricelist. In case of large Pricelists, this leads to a lot of duplicated data and organizational overhead.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
In Discount Schema (will be called Pricing Condition Schema in future) the following Fields shall be added
- Fixed add Amount: this is a Price Field. The amount in here shall be added to the price.
- Price system: this is a Price system field. This leads to a new price retrieval. In Document Lines, this Price system shall be shown as Information.
- Individual Price: this is Price Field. This price shall overwrite other retrieved price.

In document lines with Price retrieval, the fields above shall lead to price calculation.

**Comment by teosarca** [comment] 2018-04-11 07:44
### Concept

In Discount Schema -> Discount Break (M_DiscountSchemaBreak) add following fields:
* Base_PricingSystem_ID, not mandatory, lookup to M_PricingSystem_ID
* Std_AddAmt, not mandatory, Amount

Change org.adempiere.pricing.api.impl.CalculateDiscountCommand and in case the Base_PricingSystem_ID is filled, fetch all three prices from it (Standard price, Price list price, Limit price).
Add `Std_AddAmt` to standard price.
All 3 prices shall be returned in `DiscountResult` (priceListOverride, priceStdOverride, priceLimitOverride).

Next, in case the `DiscountResult` has the price overrides fields set, those prices shall be set into PricingResult (see org.adempiere.pricing.spi.impl.rules.Discount.calculate(IPricingContext, IPricingResult), after line ~174).

Make sure, in case the Base_PricingSystem_ID is not set everything works as before.

**Comment by teosarca** [comment] 2018-04-11 08:09
additionally, not related, but pls also delete org.compiere.model.MDiscountSchemaBreak.applies(BigDecimal, int, int) because it's not used.

**Comment by teosarca** [comment] 2018-04-11 21:57
btw, i think we can also drop org.adempiere.pricing.api.impl.MDiscountSchemaBL.calculatePrice(CalculateDiscountRequest)

**Comment by metas-lc** [comment] 2018-04-17 12:40
IT
1. Open Discount schema and create a new one, type Breaks
2. add a new line
=> new checkbox IsPriceOverride OK
3. set IsPriceOverride on Y
=> new mandatory field PriceBase appears OK
=> you can select either Pricing system, or Fixed
4. select Pricing system
=> new mandatory field Base_PricingSystem_ID appears
=> new field Aufschlag auf Standardpreis appears
5. on PriceBase, select Fixed instead
=> new field Standardpreis appears OK
.
Regression: tested discounts with IsPriceOverride=N
=> works as before: the discount is applied according to bpartner, product, qty, discount OK
.
6. created a new discount with 2 lines:
- product A: break value 10, discount 5, IsPriceOverride Y, Pricing system, pricelist a, Aufschlag auf Standardpreis 9
- product B:  break value 20, discount 7, IsPriceOverride Y, Fixed, standardprice 11
7. create a new sales order and add these 2 products:
product A qty 9 => price 4 (from prcelist), discount 0
product B qty 10 => price 5 (from prcelist), discount 0
product A qty 17 => price 13 (4+9), discount 5
product B qty 20 => price 11 (discount), discount 7 
OK
.
8. set to your pricelist enforce peice limit on Y
9. add product A qty 9 => price 4 (from prcelist), discount 0 - Change price to 2 => price changes back to 4 OK
10. add product B qty 10 => price 5 (from prcelist), discount 0 - Change price to 2 => price changes back to 5 OK
11. add product A qty 17 => price 13 (4+9), discount 5 - change price to 2 => price changes back to 4.2 OK
product B qty 20 => price 11 (discount), discount 7 -  change price to 2 => price changes back to 5.35 OK
.
12. add as pricelist, a purchase one, instead of sales
=> prices are considered 0.00 (Standard price, Price list price, Limit price) OK
.
.
13. in  Discount schema for product A, set Aufschlag auf Standardpreis -9. Price of that product is 7. => in orderline price is -2 OK

.
noticed that "enforce price limit" is considered only if is set in sales order price list. The one in discount is ignored. OK? 

when discount is type Flat, you should not be able to add new lines! Task: https://github.com/metasfresh/metasfresh-webui-api/issues/940

**Closed** 2018-04-18 10:36 UTC
Labels: branch:master, branch:release, branch:release-TODO, priority:high, type:enhancement
