### ISSUE TITLE
Return HU to vendor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1062] opened 2017-03-03 10:32 UTC
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, there is no possibility to send HU back to the vendor via Handling Unit Editor.
### What is the expected or desired behavior?
Provide a functionality (button) to create Vendor returns automatically in Handling Unit Editor for selected HU. Return Document must be generated w/ the needed vendor data (taken from HU) and HU must be assigned to the Return Document. HU must then be changed in status (shipped, returned?).

belongs to the main issue: https://github.com/metasfresh/metasfresh/issues/547

**Comment by metas-rc** [comment] 2017-04-24 12:44
* Questions: 
1. Do we want to see the vendor returns from the initial bestellung?
2. How is the realtion about the inout lines from an initial receipt and inout lines from a vendor return? Reason why I ask this question: would it be enough to add the initial inout line as column in the vendor return inout line or shall I make a linking table?

**Comment by metas-rc** [comment] 2017-05-02 12:19
Note fot IT:
* Regression testing for Receiving HUs in webui

**Comment by metas-dh** [comment] 2017-05-09 12:29
Results of IT1
tested on mf15, Swing

* button for return to vendor in Handling Unit POS, Handling Unit Editor: "Lieferanten Rücklieferung", OK
* pressing that button creates a new document in vendor return (Lieferantenrücklieferung) for the selected HU: OK
* vendor return includes lines for the product as well as the HU(s): OK
* vendor return includes HU assignment: OK
* vendor return created correctly if >1 HU selected / only VPI selected / TU & VPI without LU selected: OK
* vendor & vendor's address are correctly included in the vendor return: OK
* HUs included in the vendor return are marked as shipped: OK
* vendor return has the corresponding purchase order referenced, and vice versa; zoom into works fine: OK
* invoice candidates are created for the inout lines in vendor returns: OK
* original inout line from material receipt included in the vendor return (tab Attribute): OK


problems i had:
* no notification for user about the creation of the vendor return / vendor return is not opened directly (as it is for empties returns): OK?
* splitting off qty from an HU: the original HU is not aggregated anymore and can be selected for vendor return, but the newly created, aggregated HU from the split cannot be selected, NPE: NOK
* selecting only the HU on TU level (aggregated or not): Assumption failure: model not null: NOK
* zooming into the included inout line from material receipt leads to an empty window in material receipt: NOK
* the HU used in vendor return remains in HU POS, is not marked or anything in Editor: i can select the same HU (or parts of it) for another vendor return! maybe we should mark it, like e.g. the picked HUs in Verdichtung? wdyt?
* i can select a HU with >1 product on it (from joining different TUs / VPIs on the same LU), but the vendor return shows only 1 product in the inout line, 1st tab (the 4th tab, HU Assignment, shows the other product as well): shouldn't both products be shown in an inout line?
* all invoice candidates created for the vendor returns had UOM: Pce, also the ones for product, even though the product (and its price) had UOM: Kg; therefore the IC was marked inDispute=Y and Tax_Not_Found, had to add UOM conversion: NOK
* after using a HU included in a split before for the vendor return, the qty of LUs was incorrect in the inout line in vendor return sometimes, did not find a pattern yet

* again had a problem with the HU POS window & Editor closing, after using the button; the reappeared aftter a little while and the selected HU was gone; after closing and reopening the Editor, the HU was displayed there again

**Comment by metas-lc** [comment] 2017-05-09 12:38
might need to change the doctype like in the jasper docu https://github.com/metasfresh/metasfresh/issues/1305

**Comment by metas-dh** [comment] 2017-05-09 14:14
Update:
* regression testing for Receiving HUs in webui: worked fine

**Comment by metas-rc** [comment] 2017-05-12 12:38
Problems I found while dev testing:
* If HUs of different partners were selected to be returned to vendor, I got a notification only for the first vendor return being created. -> Fixed

**Comment by metas-dh** [comment] 2017-05-17 11:27
Results of IT2
tested on mf15, Swing (Windows as well)

former problems:
* no notification for user about the creation of the vendor return / vendor return is not opened directly (as it is for empties returns):  i got notifications on Windows, so it seems to be an x2go problem

* selecting only the HU on TU level (aggregated or not): Assumption failure: model not null: not happening anymore, vendor return is created, OK

* zooming into the included inout line from material receipt leads to an empty window in material receipt: also happened on Windows, so not sure if this is an x2go-only problem!

* the HU used in vendor return remains in HU POS, is not marked or anything in Editor: i can select the same HU (or parts of it) for another vendor return: this is still happening! the HU has status: Shipped, but is still displayed in HU POS; didn't we say the HUs with status: Shipped shall not be displayed in the POS windows?

* i can select a HU with >1 product on it (from joining different TUs / VPIs on the same LU), but the vendor return shows only 1 product in the inout line, 1st tab (the 4th tab, HU Assignment, shows the other product as well): shouldn't both products be shown in an inout line?
> If the join is performed before the receipt is created ( the products come directly in one box), the vendor return is correctly created: tested, OK
> But if the join is done afterwards, the assignments point to a single inoutLine. The second product is lost because of this. I think sthis will also be covered by: #1496 (metas-rc): will test again for this new task

* all invoice candidates created for the vendor returns had UOM: Pce, also the ones for product, even though the product (and its price) had UOM: Kg; therefore the IC was marked inDispute=Y and Tax_Not_Found, had to add UOM conversion: ICs now have the correct UOM, OK

* after using a HU included in a split before for the vendor return, the qty of LUs was incorrect in the inout line in vendor return sometimes, did not find a pattern yet
I think this is also linked with #1496. Let's not split HUs before oding vendor returns until we have the tracebility task done. (metas-rc): will test again for this new task

* again had a problem with the HU POS window & Editor closing, after using the button; the reappeared aftter a little while and the selected HU was gone; after closing and reopening the Editor, the HU was displayed there again: did not happen for Windows, seems to be an x2go problem

from dev-test:
* If HUs of different partners were selected to be returned to vendor, I got a notification only for the first vendor return being created: got 2 notifications (in Windows), fixed


new problems:
* when only the TU was selected for vendor return, not the LU, the vendor return document nevertheless includes the LU (its status is Destroyed in HU window), and the product is still displayed in HU POS, on VPI (or No Handling Item, as it is now called): NOK

* the invoice candidates for the product vendor returns all were marked with Error and in Dispute, bc they were supposedly missing on the pricelist, although they were in fact included in the list; only happened for the product itself, not Gebinde (happened for both new products on the pricelist as well as for product that is always included in the pricelist, from masterdata): NOK

**Comment by metas-rc** [comment] 2017-05-22 11:31
Followup created: https://github.com/metasfresh/metasfresh/issues/1603

Moving this task to Done

**Comment by metas-rc** [comment] 2017-05-23 07:03
* Please, make the vendor return be created for the warehouse of the HU.

This will be solved in https://github.com/metasfresh/metasfresh-webui-api/issues/396

**Comment by metas-rc** [comment] 2017-05-31 07:17
I think the problems found while testing are solved now. Please, retest.

**Comment by teosarca** [comment] 2017-06-06 20:46
rolled on w101

**Comment by metas-lc** [comment] 2017-06-13 16:19
I. vendor return - return entire qty

1. create a new purchase order, add a product with TU, complete

2. go to receipt pos and select your line, create receipt

3. select your line and press on korrektur
=> your HU is there

4. select the HU and do Vedor Return
=> the HU disappears and you get notification about the newly created inout

5. select the notification 
=> inout Lieferantenruklieferung opens, doctye Produktrücklieferung OK
=> inout contains 3 lines, with product, TU and LU. Qtys are set accordingly OK
=> there is 1 HU assignment OK
=> attribute is like in order, not like in inout OK?? (will document here https://github.com/metasfresh/metasfresh/issues/1603)

6. print jasper for vendor return
=> not working. will be fixed by https://github.com/metasfresh/metasfresh/issues/1793

7. open korrektur again 
=> hu is not there anymore OK

8. check HU window and POS for your HU
=> your HU is shipped and it doesn't appear in POS OK

9. receipt once again and do Vedor Return from HU POS
=> works the same OK 

II. vendor return - return partial qty

1. create a new purchase order, add a product with TU, complete

2. go to receipt pos and select your line, create receipt from 2 or more TUs (e.g. CU 10, TU 1, LU 3)

3. select your line and press on korrektur, select just 1 HU and do Vedor Return
=> works the same like in testcase I

III. vendor return - return multiple products

1. create a purchase order, add 3 products with TUs and complete

2. open all 3 products in receipt pos, each on its own LU and do receipt 
=> 1 receipt with all 3 products

3. press on korrektur and select 2 TUs, make vendor return
=> works the same
=> 2 product lines, 2 hu assignments OK
=> lines for TU and LU are added OK 


IV. vendor return - return from multiple orders and inouts

1. create 3 purchase orders, each with 1 different products, 2 with same bpartner, 1 different bpartner

2. create 3 inouts, 1 per order

3. go to HU POS and select all 3 LUs, create vendor return
=> 2 vendor returns are created with the correct qtys and bpartner
=> 2 notifications


General:

1. go to referenced documents in vendor return
=> order is referenced and vice versa
=> invoice candidates are created for each line

2. create invoice for the inout's invoice candidates lines 
=> purchase invoice, type creadit memo, qty with minus and total with plus

3. go to vendor return and select a product line. Zoom into original inout
=> original inout opens

4. when doing vendor return select only the TU (leave the LU out)
=> product and TU were added in return. LU not. Also the assignment is for TU only
=> LU is destroyed and not shown in HU POS 

5. ordering and returning a product with KG or PCE have the correct UOM in Invoice Candidates for the vendor return OK


Repeated the cases above on webui
=> works the same OK
=> note that: vendor return window doesn't have original inout field in the line

**Closed by metas-lc** 2017-06-13 16:19 UTC
Labels: branch:master, branch:release, type:enhancement
