### ISSUE TITLE
Automatic upload orders in csv file with COPY into c_olcand

### ISSUE THREAD

**Issue by nebergd** [metasfresh/metasfresh#755] opened 2016-12-23 07:08 UTC
I generate a csv file with vba in excel 2010. This file will be transfered via winscp into the folder \tmp. Server Login. su root; su metasfresh. psql metasfresh; 
COPY c_olcand FROM '/tmp/UploadAngebote.txt' DELIMITER ',' CSV HEADER;
All entrys are transfered in the DB. 
![image](https://cloud.githubusercontent.com/assets/24392763/21448707/d73db9b8-c8e5-11e6-9e7f-7aee68744ac9.png)
![image](https://cloud.githubusercontent.com/assets/24392763/21448715/e34288c4-c8e5-11e6-897f-c82f3514a797.png)
For Order Row is  no data (Zuordnung - Auftragszeile). 
There is no way at the moment to transfer the order candidate to an order.
![image](https://cloud.githubusercontent.com/assets/24392763/21448803/b6dba936-c8e6-11e6-96a2-c1b4d4b71d97.png)
![image](https://cloud.githubusercontent.com/assets/24392763/21448807/c3158f3c-c8e6-11e6-84c9-442076f7e078.png)

Dieter

**Comment by metas-ts** [comment] 2016-12-23 07:30
Hi Dieter, 
thanks for creating the issue. 
Is it possible for you to also attach a typical csv file we can use when reproducing the problem?

**Comment by nebergd** [comment] 2016-12-23 12:36
Yes we can
[UploadAngebote.txt](https://github.com/metasfresh/metasfresh/files/670790/UploadAngebote.txt)

**Comment by nebergd** [comment] 2016-12-28 10:22
Hw we see in Test
![image](https://cloud.githubusercontent.com/assets/24392763/21519754/e2cf3186-ccef-11e6-8444-7335b627a07c.png)

**Comment by metas-ts** [comment] 2016-12-28 10:40
Hi,
please try applying this SQL on your database:
```
UPDATE AD_RelationType SET InternalName='C_OLCandProcessor_1000003<=>C_OLCand' WHERE InternalName='C_OLCandProcessor_1000000<=>C_OLCand';
UPDATE AD_Reference SET Name='RelType_C_OLCandProcessor_1000003' WHERE AD_reference_ID=540475;
UPDATE AD_Ref_Table SET WhereClause='C_OLCandProcessor_ID=1000003';

UPDATE AD_Reference SET Name='RelType_C_OLCand_1000003' WHERE AD_reference_ID=540476;
UPDATE AD_Ref_Table SET WhereClause='C_OLCand.AD_InputDataSource_ID IN (150,160) AND C_OLCand.Processed=''N'' AND C_OLCand.IsActive=''Y'' AND C_OLCand.IsError=''N'' AND C_OLCand.IsImportedWithIssues=''N''' where AD_reference_ID=540476;
```
that ther that, it should work

**Comment by metas-ts** [comment] 2017-01-02 07:02
Good Morning Dieter, and a happy new year!

Tried to apply the SQL command
`COPY c_olcand FROM '/tmp/UploadAngebote.txt' DELIMITER ',' CSV HEADER;` from this issue's [first comment](https://github.com/metasfresh/metasfresh/issues/755#issue-197322883)

to the file https://github.com/metasfresh/metasfresh/files/670790/UploadAngebote.txt you provided [here](https://github.com/metasfresh/metasfresh/issues/755#issuecomment-268983890)

but it didn't work (it returned "0"). 

From the [postgres documentation](https://www.postgresql.org/docs/9.5/static/sql-copy.html) is assume that the file should have a header line and comma as delimiter, as opposed to semicolon.

Can you please check the file and/or command?

**Comment by nebergd** [comment] 2017-01-02 07:18
Hi Tobias,
also happy new year.
I check it...

**Comment by nebergd** [comment] 2017-01-02 08:36
Hi now I produce a new file.
COPY c_olcand FROM '/tmp/UploadAngebote.txt' DELIMITER ';' NULL AS '';
[UploadAngebote.txt](https://github.com/metasfresh/metasfresh/files/680547/UploadAngebote.txt)

**Comment by metas-ts** [comment] 2017-01-04 10:44
Flagged the issue as enhancement. the problem was within the masterdata see german [forum post](https://forum.metasfresh.org/t/auftragskandidat/90/26?u=metas-ts)

but the user was not shown any indication wtf the problem was. this will be fixed by PR https://github.com/metasfresh/metasfresh/pull/768

**Comment by nebergd** [comment] 2017-01-05 09:40
Hi Tobias,
i am really frustrated ... could you please try it with this file again. I could not push this ordercandidate to an order.
[UploadAngebote.txt](https://github.com/metasfresh/metasfresh/files/686892/UploadAngebote.txt)

I have no idea what the problem is. I checked the ..._id from all entrys and I found an entry in each database.
So I hope it works on your system because you use my dump.
Dieter

**Comment by metas-ts** [comment] 2017-01-05 10:10
@nebergd as just talked about in skype: the file's C_OLCand has `Processed='Y'`

**Comment by metas-dh** [comment] 2017-01-06 08:52
Integrated, built and deployed for integration test

**Comment by metas-ts** [comment] 2017-01-06 14:59
Asdiscussed, the last issue was that `AD_DataDestination_ID` was `null`.

needs to be 540003, otherwise the processor doesn't know the C_OLCand ist supposed to become an order

**Comment by metas-dh** [comment] 2017-01-11 08:13
Checked with ts: we don't have a suitable csv files with matching data in one of our dbs to test with; issue was already tested and approved by customer, so we decided to put it in done.

**Closed by metas-dh** 2017-01-11 08:13 UTC
Labels: enhancement
